language: php

php:
  - 5.6
env:
  - DB=mysql

before_script:
  - mysql -e 'create database resto_test;'
  - cd resto/
  - composer install --no-interaction

script:
  - vendor/bin/phpcs --standard=PSR1,PSR2 app/
  - vendor/bin/phpunit
  - vendor/bin/phploc app/
